### ISSUE TITLE
Set up live migration

### ISSUE THREAD

**Issue by dmsimard** [CentOS/centos-cloud#13]
cico cloud doesn't really have live migration in terms of use case but it can be convenient if need be.
It's also required to set up live migration (i.e, shared key between compute nodes) in order to be able to use the "resize" command which allows to move a virtual machine from a flavor to the other.

**Comment by arrfab** [comment]
I was myself reading what's required for openstack live migration : https://docs.openstack.org/admin-guide/compute-configuring-migrations.html#section-configuring-compute-migrations
As we have no shared storage in that env (but is that something we need/want ? ) , I guess we'll just be able to use "block live migration"

**Comment by dmsimard** [comment]
Yes, live block migration is done over rsync and typically works very well -- it just takes longer than detaching/re-attaching a volume.
It gets tricky if the paging is dirtied faster than it can be transferred but I don't think in the use cases we have this will be happening.
